// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBipoJvGPs2xANKcbszxMiZO0eFZlS7RqE',
    appId: '1:647700493345:web:0bba4776536fbbebdd5f60',
    messagingSenderId: '647700493345',
    projectId: 'testloginpage-51057',
    authDomain: 'testloginpage-51057.firebaseapp.com',
    storageBucket: 'testloginpage-51057.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOm-yNhKi0eSbPNgfHhCT6vg9hNYYzeHE',
    appId: '1:647700493345:android:5b7c76be1d846f1bdd5f60',
    messagingSenderId: '647700493345',
    projectId: 'testloginpage-51057',
    storageBucket: 'testloginpage-51057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MHn98-Rv-Pd-A6wHbfHWziWQvPhoinc',
    appId: '1:647700493345:ios:291b24b8b9d956afdd5f60',
    messagingSenderId: '647700493345',
    projectId: 'testloginpage-51057',
    storageBucket: 'testloginpage-51057.appspot.com',
    iosClientId: '647700493345-l4p4pf6m1k2s45370k61afnj98jtavhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerGoogleApRatkum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MHn98-Rv-Pd-A6wHbfHWziWQvPhoinc',
    appId: '1:647700493345:ios:5d59227a710c8590dd5f60',
    messagingSenderId: '647700493345',
    projectId: 'testloginpage-51057',
    storageBucket: 'testloginpage-51057.appspot.com',
    iosClientId: '647700493345-sucmo0voln84s0q92jnhmqpcd6jp4hds.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerGoogleApRatkum.RunnerTests',
  );
}
